### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by c0b21031** [suzukiyukito/ProjExD#1]
https://github.com/suzukiyukito/ProjExD/blob/69a4d0a6756e728cf0ec7f7db3b3dfe1adc7d1c4/kadai/alphabet.py#L6

時間制限を入れる

**Comment by suzukiyukito** [comment]
タイムの記録のことなら、すでに書いてあると思う。

**Comment by suzukiyukito** [comment]
言われたことの確認は終わっています～
