### ISSUE TITLE
些細なこと

### ISSUE THREAD

**Issue by c0b210377b** [suzukiyukito/ProjExD#11]
https://github.com/suzukiyukito/ProjExD/blob/f7d8d3b2fedcf0d062ffe2792575a713d9076268/ex04/dedge_bomb.py#L127
[ screen_rect = screen.get_rect() ]みたいに設定して、[ screen_rect.width - 40 ]みたいに書いたほうが、仮にウィンドウサイズが変更になっても対応がしやすくなると思う

**Comment by suzukiyukito** [comment]
変更されていただきました！ありがとうございました。
