### ISSUE TITLE
このコードについて

### ISSUE THREAD

**Issue by c0b210377b** [suzukiyukito/ProjExD#4]
https://github.com/suzukiyukito/ProjExD/blob/c76657ed20b21d2cf40197214010a1aa7605a8c9/ex02/calc.py#L20
もう少しコンパクトに書けるではないかと感じた。

**Comment by suzukiyukito** [comment]
私が考えた改善案としては、4×5のような電卓を下に作り、より見やすくするというものです。
しかし、それではかえって条件分岐が多くなってしまって見づらいものになってしまうのではないかなと感じています。
逆にどのように直した方かいいでしょうか？良ければ改善案をくれると助かります！
