### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by c0b210377b** [suzukiyukito/ProjExD#5]
https://github.com/suzukiyukito/ProjExD/blob/96fbf738bbdac71b6816e65713035d84729853e8/ex02/calc.py#L3
講義では登場していない高度なことをしている

**Comment by suzukiyukito** [comment]
多分、VScode上で実行してしまった時に生成されてしまったコードです。コメントありがとうございます。逆にいらないものがインポートされていることに気が付くことができました。
